/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.lang.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class App {

// ./gradlew run --args '/Users/matthewsimms/Documents/projects/401/bitmap-transformer/app/src/main/resources/BitMap.bmp /Users/matthewsimms/Documents/projects/401/bitmap-transformer/app/src/main/resources/NewBitMap.bmp flipImage'
    public static void main(String[] args) throws IOException {
        System.out.println(args[0]);

        System.out.println(args[1]);
        System.out.println(args[2]);


//        File inputFile = new File("/app/src/main/resources/BitMap.bmp");
        File inputFile = new File(args[0]);
        File outputFile = new File (args[1]);
        BufferedImage image = null;
        try {
            image = ImageIO.read(inputFile);
            System.out.println("this is the image" + image);
        }catch(IOException e){
            System.out.println("cant find the file");
        }
        if (args[2].contains("flip") ){
            Bitmap.flipImage(outputFile, image);

        }else if(args[2].contains("border")) {
            Bitmap.addBorder(outputFile, image);
        }else if(args[2].contains("grey")) {
            Bitmap.greyScale(outputFile, image);
        }else{
            Bitmap.test();
        }

//        File outputFile = new File ("/app/src/main/resources/NewBitMap.bmp");

//        System.out.println(image);

//        flipImage(args[0],args[1])


    }



    }

